export const OPTIONS = {
  framing: [
    "Extreme Close-up",
    "Close-up",
    "Medium Close-up",
    "Medium Shot",
    "Cowboy Shot",
    "Medium Full Shot",
    "Full Shot",
    "Wide Shot",
    "Extreme Wide Shot",
  ],
  lens: [
    "14mm Ultra Wide",
    "24mm Wide Angle",
    "35mm Documentary",
    "50mm Standard",
    "85mm Portrait",
    "100mm Macro",
    "200mm Telephoto",
    "400mm Super Telephoto",
    "600mm Super Telephoto",
    "Helios 44-2 58mm",
    "Laowa 24mm f/14 2x Macro Periprobe Lens",
    "Fish-eye Lens",
    "Tilt-Shift Lens",
  ],
  lensType: [
    "Spherical",
    "Anamorphic",
  ],
  fStops: [
    "None", "f/1.2", "f/1.4", "f/1.8", "f/2", "f/2.8", "f/4", "f/5.6", "f/8", "f/11", "f/16", "f/22"
  ],
  lighting: [
    "Golden Hour",
    "Blue Hour",
    "Studio Lighting",
    "Cinematic Lighting",
    "Rembrandt Lighting",
    "Neon Lighting",
    "Harsh Sunlight",
    "Overcast Flat Light",
    "Volumetric Lighting",
    "Bioluminescence",
  ],
  medium: [
    "Digital Photography",
    "35mm Film",
    "Polaroid",
    "Oil Painting",
    "Watercolor",
    "Concept Art",
    "3D Render (Unreal Engine 5)",
    "Anime Style",
    "Vector Illustration",
    "Cyberpunk",
  ],
  colorGrading: [
    "High Contrast",
    "Muted Colors",
    "Pastel Tones",
    "Monochrome / Black & White",
    "Teal and Orange",
    "Vibrant / Saturated",
    "Sepia Tone",
    "Cyberpunk Neon",
  ],
  aspectRatio: [
    "1:1",
    "4:3",
    "3:4",
    "16:9",
    "9:16",
    "21:9",
  ],
  subjectType: [
    "Human",
    "Cyborg",
    "Elf",
    "Animal",
    "Robot",
    "Alien",
    "Vampire",
    "Deity",
  ],
  gender: [
    "Female",
    "Male",
    "Androgynous",
    "Non-binary",
  ],
  race: [
    "Black",
    "White",
    "Coloured / Mixed",
    "Asian",
    "Hispanic / Latino",
    "Indigenous",
    "Middle Eastern",
  ],
  ethnicity: [
    "South African",
    "Nigerian",
    "Kenyan",
    "Japanese",
    "Chinese",
    "Korean",
    "Indian",
    "British",
    "American",
    "Brazilian",
    "Mexican",
    "German",
    "French",
  ],
  age: [
    "Child",
    "Teenager",
    "Young Adult",
    "Middle-aged",
    "Elderly",
  ],
  build: [
    "Slender",
    "Athletic",
    "Muscular",
    "Curvy",
    "Stocky",
    "Plus-size",
  ],
  skinTone: [
    "Fair",
    "Light",
    "Dark Brown",
    "Deep Brown",
  ],
  skinAndHandTexture: [
    "Soft Feminine",
    "Muscular",
    "Dirty/Gritty",
    "Hardworking Hands",
    "Wrinkled/Aged Hands",
  ],
  hairTexture: [
    "4C Afro",
    "4A Coiled",
    "Coarse Kinky",
    "Curly",
    "Straight",
    "Wavy",
  ],
  hairStyle: [
    "Bun",
    "Fade",
    "Brush Cut",
    "Braids",
    "Dreadlocks",
    "Layered",
    "Ponytail",
  ],
  hairColor: [
    "Jet Black",
    "Natural Brown",
    "Blonde",
    "Auburn",
    "Silver/Grey",
    "Vibrant/Coloured",
  ],
  expression: [
    "Looking directly at camera",
    "Eyes closed",
    "Looking upward",
    "Looking downward",
    "Distant/Thoughtful gaze",
  ],
  bodyPoseAndMovement: [
    "Sitting pose",
    "Dynamic movement",
    "Standing portrait",
    "Hand positioned near face",
    "Relaxed stance",
  ],
  locationType: [
    "Interior",
    "Exterior",
  ],
  locationSpace: [
    "Home",
    "Garden",
    "Street",
    "City",
    "Office",
    "Cafe",
    "Restaurant",
    "Club",
    "Forest",
    "Beach",
    "Mountain",
    "Desert",
    "Space Station",
    "Studio",
    "Warehouse",
  ],
  lifestyleClass: [
    "Working Class / Blue Collar",
    "Middle Class / Suburban",
    "Upper-Middle Class / Affluent",
    "Luxury / High-Net-Worth",
    "Bohemian / Artistic",
    "Urban Professional",
    "Rural / Agricultural",
  ],
  timeOfDay: [
    "Dawn",
    "Morning",
    "Midday / Noon",
    "Afternoon",
    "Golden Hour",
    "Evening",
    "Dusk / Twilight",
    "Night",
    "Midnight",
  ],
};

export const DEFAULT_STATE = {
  // Technical
  useReferenceTechnical: false,
  framing: "",
  lens: "",
  lensType: "",
  fStopIndex: 0,
  lighting: "",
  medium: "",
  colorGrading: "",
  aspectRatio: "",
  // Subject
  useReferenceSubject: false,
  subjectType: "",
  gender: "",
  race: "",
  ethnicity: "",
  skinTone: "",
  skinAndHandTexture: "",
  age: "",
  build: "",
  hairTexture: "",
  hairStyle: "",
  hairColor: "",
  expression: "",
  bodyPoseAndMovement: "",
  lifestyleClass: "",
  clothingStyle: "",
  accessories: "",
  // Supporting Subject
  useReferenceSupportingSubject: false,
  supportingSubjectType: "",
  supportingGender: "",
  supportingRace: "",
  supportingEthnicity: "",
  supportingSkinTone: "",
  supportingSkinAndHandTexture: "",
  supportingAge: "",
  supportingBuild: "",
  supportingHairTexture: "",
  supportingHairStyle: "",
  supportingHairColor: "",
  supportingExpression: "",
  supportingBodyPoseAndMovement: "",
  supportingLifestyleClass: "",
  supportingClothingStyle: "",
  supportingAccessories: "",
  // Environment
  useReferenceEnvironment: false,
  locationType: "",
  locationSpace: "",
  envLifestyleClass: "",
  timeOfDay: "",
  exactLocation: "",
  environmentDescriptor: "",
  coordinates: "",
  // Overrides
  useReferenceOverrides: false,
  coreAction: "",
  wardrobe: "",
  negativePrompt: "",
};
