export const OPTIONS = {
  cameraShotSize: [
    "Extreme Long Shot (ELS)",
    "Long Shot (LS)",
    "Extreme Wide Shot (EWS)",
    "Wide Shot (WS)",
    "Medium Long Shot (MLS) / Medium Wide Shot (MWS)",
    "Cowboy Shot (CS)",
    "Medium Shot (MS)",
    "Medium Close-Up (MCU)",
    "Close-Up (CU)",
    "Extreme Close-Up (ECU)",
  ],
  multiSubjectFraming: [
    "Single Shot",
    "Two-Shot",
    "Three-Shot",
    "Over-the-Shoulder (OTS)",
    "Point-of-View (POV)",
  ],
  cameraAngle: [
    "Bird's-Eye View",
    "Overhead Shot",
    "Eye-Level Shot",
    "Low Angle Shot",
    "High Angle Shot",
    "Dutch Tilt",
    "Worm's-Eye View",
  ],
  lens: [
    "14mm Ultra Wide",
    "24mm Wide Angle",
    "35mm Documentary",
    "50mm Standard",
    "85mm Portrait",
    "100mm Macro",
    "200mm Telephoto",
    "400mm Super Telephoto",
    "600mm Super Telephoto",
    "Helios 44-2 58mm",
    "Laowa 24mm f/14 2x Macro Periprobe Lens",
    "Fish-eye Lens",
    "Tilt-Shift Lens",
  ],
  lensType: [
    "Spherical",
    "Anamorphic",
  ],
  fStops: [
    "None", "f/1.2", "f/1.4", "f/1.8", "f/2", "f/2.8", "f/4", "f/5.6", "f/8", "f/11", "f/16", "f/22"
  ],
  lighting: [
    "Golden Hour",
    "Blue Hour",
    "Studio Lighting",
    "Cinematic Lighting",
    "Rembrandt Lighting",
    "Neon Lighting",
    "Harsh Sunlight",
    "Overcast Flat Light",
    "Volumetric Lighting",
    "Bioluminescence",
  ],
  medium: [
    "Digital Photography",
    "Concept Art",
    "Anime Style",
    "Vector Illustration",
    "Painting",
    "3D Render",
  ],
  colorGrading: [
    "High Contrast",
    "Muted Colors",
    "Pastel Tones",
    "Monochrome / Black & White",
    "Teal and Orange",
    "Vibrant / Saturated",
    "Sepia Tone",
    "Cyberpunk Neon",
  ],
  aspectRatio: [
    "1:1",
    "4:3",
    "3:4",
    "16:9",
    "9:16",
    "21:9",
  ],
  subjectType: [
    "Human",
    "Cyborg",
    "Elf",
    "Animal",
    "Robot",
    "Alien",
    "Vampire",
    "Deity",
  ],
  gender: [
    "Female",
    "Male",
    "Androgynous",
    "Non-binary",
  ],
  race: [
    "Black",
    "White",
    "Coloured / Mixed",
    "Asian",
    "Hispanic / Latino",
    "Indigenous",
    "Middle Eastern",
  ],
  ethnicity: [
    "South African",
    "Nigerian",
    "Kenyan",
    "Japanese",
    "Chinese",
    "Korean",
    "Indian",
    "British",
    "American",
    "Brazilian",
    "Mexican",
    "German",
    "French",
  ],
  age: [
    "Child",
    "Teenager",
    "Young Adult",
    "Middle-aged",
    "Elderly",
  ],
  build: [
    "Slender",
    "Athletic",
    "Muscular",
    "Curvy",
    "Stocky",
    "Plus-size",
  ],
  skinTone: [
    "Fair",
    "Light",
    "Dark Brown",
    "Deep Brown",
  ],
  skinAndHandTexture: [
    "Soft Feminine",
    "Muscular",
    "Dirty/Gritty",
    "Hardworking Hands",
    "Wrinkled/Aged Hands",
  ],
  hairTexture: [
    "4C Afro",
    "4A Coiled",
    "Coarse Kinky",
    "Curly",
    "Straight",
    "Wavy",
  ],
  hairStyle: [
    "Bun",
    "Fade",
    "Brush Cut",
    "Braids",
    "Dreadlocks",
    "Layered",
    "Ponytail",
  ],
  hairColor: [
    "Jet Black",
    "Natural Brown",
    "Blonde",
    "Auburn",
    "Silver/Grey",
    "Vibrant/Coloured",
  ],
  expression: [
    "Looking directly at camera",
    "Eyes closed",
    "Looking upward",
    "Looking downward",
    "Distant/Thoughtful gaze",
  ],
  bodyPoseAndMovement: [
    "Sitting pose",
    "Dynamic movement",
    "Standing portrait",
    "Hand positioned near face",
    "Relaxed stance",
  ],
  locationType: [
    "Interior",
    "Exterior",
  ],
  locationSpace: [
    "Home",
    "Garden",
    "Street",
    "City",
    "Office",
    "Cafe",
    "Restaurant",
    "Club",
    "Forest",
    "Beach",
    "Mountain",
    "Desert",
    "Space Station",
    "Studio",
    "Warehouse",
  ],
  lifestyleClass: [
    "Working Class / Blue Collar",
    "Middle Class / Suburban",
    "Upper-Middle Class / Affluent",
    "Luxury / High-Net-Worth",
    "Bohemian / Artistic",
    "Urban Professional",
    "Rural / Agricultural",
  ],
  timeOfDay: [
    "Dawn",
    "Morning",
    "Midday / Noon",
    "Afternoon",
    "Golden Hour",
    "Evening",
    "Dusk / Twilight",
    "Night",
    "Midnight",
  ],
  objectType: [
    "Electronics / Tech",
    "Furniture",
    "Vehicle",
    "Food / Beverage",
    "Apparel / Fashion",
    "Packaging",
    "Gadget / Tool",
    "Cosmetics / Beauty",
    "Artwork / Decor",
    "Jewelry",
  ],
  objectMaterial: [
    "Matte",
    "Glossy",
    "Metallic",
    "Brushed Metal",
    "Wood",
    "Glass",
    "Plastic",
    "Leather",
    "Fabric",
    "Ceramic",
    "Concrete",
    "Marble",
  ],
  objectCondition: [
    "Brand New / Pristine",
    "Vintage",
    "Worn out / Distressed",
    "Antique",
    "Broken / Shattered",
    "Glowing / Luminous",
    "Wet / Condensation",
    "Dusty",
  ],
  objectPlacement: [
    "Floating / Levitating",
    "On a pedestal",
    "Flat lay",
    "In-hand",
    "Resting on a surface",
    "Suspended by strings",
    "Sinking in liquid",
  ],
  objectScale: [
    "Macro / Microscopic",
    "Miniature",
    "Life-sized",
    "Larger than life",
    "Giant / Monumental",
  ],
};

export const DEFAULT_STATE = {
  // Technical
  useReferenceTechnical: false,
  cameraShotSize: "",
  multiSubjectFraming: "",
  cameraAngle: "",
  lens: "",
  lensType: "",
  fStopIndex: 0,
  lighting: "",
  medium: "",
  colorGrading: "",
  aspectRatio: "",
  technicalCustom: "",
  // Subject
  useReferenceSubject: false,
  subjectType: "",
  gender: "",
  race: "",
  ethnicity: "",
  skinTone: "",
  skinAndHandTexture: "",
  age: "",
  build: "",
  hairTexture: "",
  hairStyle: "",
  hairColor: "",
  expression: "",
  bodyPoseAndMovement: "",
  lifestyleClass: "",
  clothingStyle: "",
  accessories: "",
  subjectCustom: "",
  // Supporting Subject
  useReferenceSupportingSubject: false,
  supportingSubjectType: "",
  supportingGender: "",
  supportingRace: "",
  supportingEthnicity: "",
  supportingSkinTone: "",
  supportingSkinAndHandTexture: "",
  supportingAge: "",
  supportingBuild: "",
  supportingHairTexture: "",
  supportingHairStyle: "",
  supportingHairColor: "",
  supportingExpression: "",
  supportingBodyPoseAndMovement: "",
  supportingLifestyleClass: "",
  supportingClothingStyle: "",
  supportingAccessories: "",
  supportingSubjectCustom: "",
  // Environment
  useReferenceEnvironment: false,
  locationType: "",
  locationSpace: "",
  envLifestyleClass: "",
  timeOfDay: "",
  exactLocation: "",
  environmentDescriptor: "",
  coordinates: "",
  // Overrides
  useReferenceOverrides: false,
  coreAction: "",
  wardrobe: "",
  negativePrompt: "",
  // Object / Product
  useReferenceObject: false,
  objectType: "",
  objectMaterial: "",
  objectCondition: "",
  objectPrimaryColor: "",
  objectPlacement: "",
  objectScale: "",
  objectCustom: "",
};
